dev:
  dbName: "infuser_author"
  dbType: "mysql"
  host: "localhost"
  port: 3306
  user: ""
  password: ""

prod:
  dbName: "infuser_author"
  dbType: "mysql"
  host: "localhost"
  port: 3306
  user: ""
  password: ""